myprog : main.o rb_tree.o
	gcc -g -ansi -Wall main.o rb_tree.o -o myprog
main.o : main.c rb_tree.h
	gcc -c -ansi -Wall main.c -o main.o 
rb_tree.o : rb_tree.c rb_tree.h
	gcc -c -ansi -Wall rb_tree.c -o rb_tree.o




